ifdef BR2_PACKAGE_FS_CUSTOMIZATION_NONE
endif

ifdef BR2_PACKAGE_FS_CUSTOMIZATION_POLYSAT
FS_CUSTOMIZATIONS_BASE_NAME:=fs_customizations
FS_CUSTOMIZATIONS_SITE:=git@asof.atl.calpoly.edu:generic_filesystem.git
FS_CUSTOMIZATIONS_SITE_METHOD:=git
FS_CUSTOMIZATIONS_INSTALL_TARGET=YES
TARGET_CUSTOM_FILES_PATH=$(FS_CUSTOMIZATIONS_DIR)

ifeq ($(BR2_PACKAGE_FS_CUSTOMIZATION_POLYSAT_version_head),y)
   #FS_CUSTOMIZATIONS_VERSION:=HEAD
   FS_CUSTOMIZATIONS_VERSION:=$(shell git ls-remote $(FS_CUSTOMIZATIONS_SITE) | grep HEAD | head -1 | sed -e 's/[ \t]*HEAD//')
endif

ifeq ($(BR2_PACKAGE_FS_CUSTOMIZATION_POLYSAT_version_custom),y)
   FS_CUSTOMIZATIONS_VERSION:=$(subst ",,$(BR2_PACKAGE_FS_CUSTOMIZATION_CONFIG_CUSTOM_VERSION_STR))
endif

ifeq ($(BR2_PACKAGE_FS_CUSTOMIZATION_POLYSAT_version_1_10),y)
   FS_CUSTOMIZATIONS_VERSION:=v1.10
endif

FS_CUSTOMIZATIONS_VERSION?=v1.10
FS_CUSTOMIZATIONS_SOURCE:=fs_customizations-$(FS_CUSTOMIZATIONS_VERSION).tgz


$(eval $(call GENTARGETS,package,fs_customizations))

TARGETS+=fs_customizations
endif

ifdef BR2_PACKAGE_FS_CUSTOMIZATION_FOLDER
TARGET_CUSTOM_FILES_PATH=$(BR2_PACKAGE_FS_CUSTOMIZATION_PATH)
endif
